spring:
  datasource:
    name: project
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 12345


  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080


